import { react } from "@vllnt/eslint-config";

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "scripts/**",
      "eslint.config.js",
      "babel.config.cjs",
      "jest.config.cjs",
      "jest.setup.cjs",
      "tsup.config.ts",
    ],
  },
  ...react,
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      "@next/next/no-html-link-for-pages": "off",
      "jsx-a11y/label-has-associated-control": "off",
    },
  },
  {
    files: ["src/index.ts"],
    rules: {
      "simple-import-sort/exports": "off",
    },
  },
  {
    files: ["**/*.test.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "functional/no-loop-statements": "off",
      "max-lines-per-function": "off",
    },
  },
  {
    files: [
      "src/components/alert-dialog/**",
      "src/components/animated-tabs/**",
      "src/components/animated-testimonials/**",
      "src/components/breadcrumb/**",
      "src/components/button-group/**",
      "src/components/calendar/**",
      "src/components/carousel/**",
      "src/components/category-filter/**",
      "src/components/checkbox-group/**",
      "src/components/checkbox/**",
      "src/components/checklist/**",
      "src/components/collapsible/**",
      "src/components/color-picker/**",
      "src/components/completion-dialog/**",
      "src/components/combobox/**",
      "src/components/command/**",
      "src/components/context-menu/**",
      "src/components/copy-button/**",
      "src/components/date-field/**",
      "src/components/date-picker/**",
      "src/components/date-range-picker/**",
      "src/components/dialog/**",
      "src/components/drawer/**",
      "src/components/dropdown-menu/**",
      "src/components/exercise/**",
      "src/components/faq/**",
      "src/components/file-upload/**",
      "src/components/flashcard/**",
      "src/components/filter-bar/**",
      "src/components/floating-toolbar/**",
      "src/components/form/**",
      "src/components/input-otp/**",
      "src/components/interactive-timeline/**",
      "src/components/keyboard-shortcuts-help/**",
      "src/components/link/**",
      "src/components/list-box/**",
      "src/components/menubar/**",
      "src/components/multi-select/**",
      "src/components/native-select/**",
      "src/components/navigation-menu/**",
      "src/components/pagination/**",
      "src/components/popover/**",
      "src/components/progress-tracker/**",
      "src/components/quiz/**",
      "src/components/radio-group/**",
      "src/components/range-calendar/**",
      "src/components/search-dialog/**",
      "src/components/segmented-control/**",
      "src/components/select/**",
      "src/components/share-dialog/**",
      "src/components/sheet/**",
      "src/components/sidebar/**",
      "src/components/slideshow/**",
      "src/components/slider/**",
      "src/components/step-by-step/**",
      "src/components/step-navigation/**",
      "src/components/stepper/**",
      "src/components/tabs/**",
      "src/components/tag-group/**",
      "src/components/tags-input/**",
      "src/components/time-field/**",
      "src/components/time-picker/**",
      "src/components/timeline-scrubber/**",
      "src/components/toast/**",
      "src/components/toggle-group/**",
      "src/components/toggle/**",
      "src/components/toolbar/**",
      "src/components/tooltip/**",
      "src/components/tour/**",
      "src/components/tree-view/**",
      "src/components/tutorial-complete/**",
      "src/components/tutorial-filters/**",
      "src/components/view-switcher/**",
      "src/components/workspace-switcher/**",
    ],
    rules: {
      "functional/no-loop-statements": "off",
      "jsx-a11y/no-autofocus": "off",
      "max-lines-per-function": "off",
      "max-params": "off",
      "no-restricted-syntax": "off",
      "no-unreachable-loop": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/refs": "off",
      "react/jsx-handler-names": "off",
      "unicorn/consistent-destructuring": "off",
      "unicorn/consistent-function-scoping": "off",
      "write-good-comments/write-good-comments": "off",
    },
  },
];
