import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts', 'src/tailwind-preset.ts'],
  format: ['esm'],
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'next',
    'next/navigation',
    'next/link',
    'next/image',
    'next-themes',
    /^@radix-ui\//,
    /^@tanstack\//,
    /^@xyflow\//,
    /^@mdx-js\//,
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    'cmdk',
    'embla-carousel-react',
    'html-to-image',
    'input-otp',
    'lucide-react',
    'react-day-picker',
    'react-markdown',
    'react-resizable-panels',
    'react-syntax-highlighter',
    'sonner',
    'vaul',
    'tailwindcss',
    'tailwindcss-animate',
  ],
  target: 'es2020',
  tsconfig: 'tsconfig.build.json',
})
